# Generated by Django 5.1.3 on 2024-11-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(max_length=20, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('edition', models.CharField(blank=True, max_length=100, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('date_borrowed', models.DateTimeField(blank=True, null=True)),
                ('days_remaining', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('borrowed', 'Borrowed'), ('available', 'Available'), ('returned', 'Returned')], default='available', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff')], max_length=10)),
            ],
        ),
    ]
