# Generated by Django 5.1.2 on 2024-11-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("libapp", "0003_remove_book_edition_remove_book_isbn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="days_remaining",
            field=models.IntegerField(),
        ),
    ]
