# Generated by Django 5.1.2 on 2024-11-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(max_length=20, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('edition', models.CharField(blank=True, max_length=50, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('pages', models.PositiveIntegerField(blank=True, max_length=6, null=True)),
                ('publisher', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(max_length=4)),
                ('isbn', models.CharField(max_length=30, unique=True)),
                ('date_to_return', models.PositiveIntegerField(max_length=2)),
            ],
        ),
    ]
