# Generated by Django 5.1.3 on 2024-11-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0002_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
    ]
