# Generated by Django 5.1.2 on 2024-11-30 04:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("libapp", "0004_alter_book_days_remaining"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="days_remaining",
        ),
    ]
